WIP: manually recreate libstdc++ symlinks in ci-conda images
rapidsai/ci-imgs pull request #186
Opened 2024-09-03 22:14 UTC by jameslamb

Related to https://github.com/rapidsai/ci-imgs/issues/185#issuecomment-2327478322.

That issue has MUCH more detail, but in short:

* the way we build `ci-conda` images results in symlinks from `libdstc++.so` to the fully-qualified `libstdc++.so.6.0.33` (or similar) being destroyed
* that results in the system `libdstc++` being used instead of conda's
* that results in issues about missing GLIBCXX symbols (in the case where the system one is older than the one used at build time for libraries conda wants to load)

This PR is a hack to unblock CI... by manually recreating those symlinks where necessary.

2024-09-03 23:03 UTC, hcho3 approved these changes

2024-09-04 01:23 UTC, vyasr requested changes
I'd like to propose an alternate, hopefully more robust solution to the problem. [I posted it on the issue](https://github.com/rapidsai/ci-imgs/issues/185#issuecomment-2327725065).

2024-09-04 17:08 UTC, vyasr approved these changes
One typo otherwise LGTM.

2024-09-04 17:08 UTC, vyasr commented on ci-conda.Dockerfile
> +# and older conda with newer packages still works well
```suggestion
# an older conda with newer packages still works well
```

2024-09-04 17:57 UTC, jameslamb commented on ci-conda.Dockerfile
> +# and older conda with newer packages still works well
🙈 thank you

2024-09-04 19:13 UTC, merged